# 1B.1 Basis NumPy oefeningen

Hieronder vind je korte oefeningen die kunnen helpen de basis-syntax van NumPy onder de knie te krijgen.

## Sudoku

Gegeven een 6x6 sudoku:

<table border="1" cellpadding="1" cellspacing="1" style="width:500px;">
	<tbody>
		<tr>
			<td>4</td>
			<td>3</td>
			<td>2</td>
			<td>6</td>
			<td>5</td>
			<td>1</td>
		</tr>
		<tr>
			<td>1</td>
			<td>5</td>
			<td>4</td>
			<td>3</td>
			<td>6</td>
			<td>2</td>
		</tr>
		<tr>
			<td>6</td>
			<td>2</td>
			<td>5</td>
			<td>1</td>
			<td>4</td>
			<td>3</td>
		</tr>
		<tr>
			<td>2</td>
			<td>6</td>
			<td>3</td>
			<td>5</td>
			<td>1</td>
			<td>4</td>
		</tr>
		<tr>
			<td>5</td>
			<td>4</td>
			<td>1</td>
			<td>2</td>
			<td>3</td>
			<td>6</td>
		</tr>
		<tr>
			<td>3</td>
			<td>1</td>
			<td>6</td>
			<td>4</td>
			<td>2</td>
			<td>5</td>
		</tr>
	</tbody>
</table>

<p>&nbsp;</p>


We maken deze sudoku aan als een NumPy matrix en geven de totale som op 2 manieren:

In [1]:
import numpy as np

matrix = np.array(
    [[4,3,2,6,5,1],
     [1,5,4,3,6,2],
     [6,2,5,1,4,3],
     [2,6,3,5,1,4],
     [5,4,1,2,3,6],
     [3,1,6,4,2,5]])
print(matrix)
print(type(matrix))
print('Som:', np.sum(matrix))
print('Som:', matrix.sum())

[[4 3 2 6 5 1]
 [1 5 4 3 6 2]
 [6 2 5 1 4 3]
 [2 6 3 5 1 4]
 [5 4 1 2 3 6]
 [3 1 6 4 2 5]]
<class 'numpy.ndarray'>
Som: 126
Som: 126


### Vraag 1

Loop door alle rijen en check of hun som inderdaad 1+2+3+4+5+6=21 is. Je kan simpelweg door de rijen lopen door ofwel te loopen over het aantal rijen en de index te selecteren in de matrix, of de matrix zelf te itereren (waardoor je rij per rij terugkrijgt):

In [ ]:
print('Aantal rijen:', matrix.shape[0])
print('Aantal kolommen:', matrix.shape[1])

# ...

Aantal rijen: 6
Aantal kolommen: 6
Som rij 0 21
Som rij 1 21
Som rij 2 21
Som rij 3 21
Som rij 4 21
Som rij 5 21


### Vraag 2

Doe nu hetzelfde voor de kolommen:

In [ ]:
# ...

Som kolom 0: 21
Som kolom 1: 21
Som kolom 2: 21
Som kolom 3: 21
Som kolom 4: 21
Som kolom 5: 21


### Vraag 3

Vermenigvuldig elk element van de matrix met 10:

In [ ]:
# ...

[[40 30 20 60 50 10]
 [10 50 40 30 60 20]
 [60 20 50 10 40 30]
 [20 60 30 50 10 40]
 [50 40 10 20 30 60]
 [30 10 60 40 20 50]]


Vermendigvuldig elk element van elke rij met de rij-index (vanaf 0):

In [ ]:
# ...

Rij 0: [0 0 0 0 0 0]
Rij 1: [1 5 4 3 6 2]
Rij 2: [12  4 10  2  8  6]
Rij 3: [ 6 18  9 15  3 12]
Rij 4: [20 16  4  8 12 24]
Rij 5: [15  5 30 20 10 25]


### Vraag 4

Vind alle (x,y)-paren waar een 5 staat in de matrix. Dit kan met:
- `where()`, dan krijg je een tupel van lijsten terug met de verschillende x/y-waarden
- `for`-lus

#### Met `where()`:

In [ ]:
# met where()
indices_5 = # ...
indices_5

(array([0, 1, 2, 3, 4, 5], dtype=int64),
 array([4, 1, 2, 3, 0, 5], dtype=int64))

Het resultaat van `where()` is lastig om te zetten in paren. `indices_5` is een tupel van 2 NumPy reeksen, die kunnen we overlopen en samenvoegen:

In [ ]:
resultaat = []
# ...
print(resultaat)

[(0, 4), (1, 1), (2, 2), (3, 3), (4, 0), (5, 5)]


#### Met `for`:

In [ ]:
resultaat = []
# ...
            
print('Resultaat:', resultaat)

Resultaat: [(0, 4), (1, 1), (2, 2), (3, 3), (4, 0), (5, 5)]


### Vraag 5

Vind de kleine matrix die zich bevindt tussen de 'buitenranden' van de grote matrix (dus de eerste/laatste rijen/kolommen eraf) met 1 lijn code:

In [ ]:
# ...
print(kleine_matrix)

[[5 4 3 6]
 [2 5 1 4]
 [6 3 5 1]
 [4 1 2 3]]


## Punten analyseren

Gegeven: punten van 10 studenten (rijen) voor 6 vakken (kolommen):

In [ ]:
import numpy as np

np.random.seed(15)

punten = np.random.randint(1, 20, (10, 6))  # random nummers tussen 1 en 20
print(punten)

[[ 9 13  6  1  8 12]
 [16 18 14  1 11 16]
 [ 5 10  8  6 13 14]
 [16  7 16 19 18  2]
 [ 1  3 12 19  2  9]
 [ 7 10  3  9  9 16]
 [ 4  5  8  3 11  1]
 [ 6  8  6 14 18 17]
 [ 9 13 15 13  2  3]
 [13 11 18  3 19 17]]


### Vraag 1

Vind de som van elke rij

In [ ]:
som_elke_rij = # ...

print('Som van elke rij:', som_elke_rij)

Som van elke rij: [49 76 56 78 46 54 32 69 55 81]


### Vraag 2

Vind de som van de de originele matrix en de nieuwe matrix met dezelfde vorm die de bonuspunten bevat:

In [ ]:
bonuspunten = np.random.randint(1, 3, (10, 6))
print('Bonuspunten:\n', bonuspunten)

som = # ...

print('Som van alle punten:\n', som)

Bonuspunten:
 [[2 1 1 2 1 1]
 [1 1 2 2 1 2]
 [1 1 2 1 1 1]
 [1 1 2 1 1 2]
 [1 1 1 1 1 2]
 [2 2 1 2 2 1]
 [2 2 1 2 2 1]
 [1 2 1 1 2 1]
 [1 2 1 1 1 2]
 [1 1 2 2 2 2]]
Som van alle punten:
 [[11 14  7  3  9 13]
 [17 19 16  3 12 18]
 [ 6 11 10  7 14 15]
 [17  8 18 20 19  4]
 [ 2  4 13 20  3 11]
 [ 9 12  4 11 11 17]
 [ 6  7  9  5 13  2]
 [ 7 10  7 15 20 18]
 [10 15 16 14  3  5]
 [14 12 20  5 21 19]]


Sommige studenten hebben nu teveel punten. Verander de `som`-matrix zodat de punten boven de 20 worden omgezet naar 20:

In [ ]:
som_nieuw = # ...

som_nieuw

array([[11, 14,  7,  3,  9, 13],
       [17, 19, 16,  3, 12, 18],
       [ 6, 11, 10,  7, 14, 15],
       [17,  8, 18, 20, 19,  4],
       [ 2,  4, 13, 20,  3, 11],
       [ 9, 12,  4, 11, 11, 17],
       [ 6,  7,  9,  5, 13,  2],
       [ 7, 10,  7, 15, 20, 18],
       [10, 15, 16, 14,  3,  5],
       [14, 12, 20,  5, 20, 19]])

### Vraag 3

Voeg de bonuspunten toe als aparte kolommen:

In [ ]:
totaal = # ...

print('Alle punten over 2 jaar:\n', totaal)
print('Vorm van de matrix:', totaal.shape)

Alle punten over 2 jaar:
 [[ 9 13  6  1  8 12  2  1  1  2  1  1]
 [16 18 14  1 11 16  1  1  2  2  1  2]
 [ 5 10  8  6 13 14  1  1  2  1  1  1]
 [16  7 16 19 18  2  1  1  2  1  1  2]
 [ 1  3 12 19  2  9  1  1  1  1  1  2]
 [ 7 10  3  9  9 16  2  2  1  2  2  1]
 [ 4  5  8  3 11  1  2  2  1  2  2  1]
 [ 6  8  6 14 18 17  1  2  1  1  2  1]
 [ 9 13 15 13  2  3  1  2  1  1  1  2]
 [13 11 18  3 19 17  1  1  2  2  2  2]]
Vorm van de matrix: (10, 12)


### Vraag 4

Geef het gemiddelde van elke kolom uit `totaal` (per vak):

In [ ]:
gemiddeldes_kolom = # ...

print(gemiddeldes_kolom)

[ 8.6  9.8 10.6  8.8 11.1 10.7  1.3  1.4  1.4  1.5  1.4  1.5]


Geef het gemiddelde van elke rij in `totaal` (per student):

In [ ]:
gemiddelde_student = # ...

print(gemiddelde_student)

[4.75       7.08333333 5.25       7.16666667 4.41666667 5.33333333
 3.5        6.41666667 5.25       7.58333333]


### Vraag 5

Vermenigvuldig elke even kolom van `totaal` (beginnend bij 0) uit het totaal met 5:

In [ ]:
nieuw_totaal = # ...

print(nieuw_totaal)

[[45 30 40 10  5  5]
 [80 70 55  5 10  5]
 [25 40 65  5 10  5]
 [80 80 90  5 10  5]
 [ 5 60 10  5  5  5]
 [35 15 45 10  5 10]
 [20 40 55 10  5 10]
 [30 30 90  5  5 10]
 [45 75 10  5  5  5]
 [65 90 95  5 10 10]]
