# 1B.1. Voorbeeld examenvragen — lees, voorspel, verbeter

Hieronder staat telkens een (bijna) volledige oplossing voor een examenvraag. Er zitten één of meerdere bugs in die de assert doen falen (of een fout antwoord opleveren) — vaak gaat het om een verkeerd begrip van hoe de code zich gedraagt (bv. verwarring tussen een as in NumPy/Pandas, een voorwaarde die over de verkeerde scope gaat, een berekening die buiten een lus staat) in plaats van één fout symbool. Lees de code, **voorspel** de output, run, en zoek alle fouten voor je de oplossing bekijkt.

## Vraag 1: vind_matrix_eigenschappen

Opgegeven: een matrix als NumPy `array` object. Deze functie moet controleren of de matrix vierkant is. Indien zo, moet er ook gecontroleerd worden of alle cijfers op de diagonaal van de matrix (van linksboven tot rechtsonder) hetzelfde zijn. De antwoorden (beide booleans) staan in `is_vierkant` en `diagonaal_juist`.

In [1]:
import numpy as np

def vind_matrix_eigenschappen(np_matrix):
    is_vierkant = False
    diagonaal_juist = False

    print('Vorm van de matrix:', np_matrix.shape)
    if np_matrix.shape[-1] == np_matrix.shape[-1]:
        is_vierkant = True

    if is_vierkant:
        diagonaal_juist = True
        te_zoeken = np_matrix[0, 0]
        for i in range(len(np_matrix)):
            if not np_matrix[i, i] is te_zoeken:
                diagonaal_juist = False
                break

    return is_vierkant, diagonaal_juist

matrix1 = np.array([[1]])
is_v, diag = vind_matrix_eigenschappen(matrix1)
print('Vierkant?', is_v)
print('Diagonaal juist?', diag)
assert is_v == True
assert diag == True

matrix2 = np.array([[1, 2, 3], [4, 5, 6]])
is_v, diag = vind_matrix_eigenschappen(matrix2)
print('Vierkant?', is_v)
print('Diagonaal juist?', diag)
assert is_v == False
assert diag == False

Vorm van de matrix: (1, 1)
Vierkant? True
Diagonaal juist? False


AssertionError: 

**Wat gaat hier mis? Schrijf je antwoord + fix hieronder voor je verder scrolt.**

## Vraag 2: vermenigvuldig

Deze functie maakt een `factors`-matrix met dezelfde vorm als `matrix`: `factor` op de diagonaal, `factor - 1` overal elders. Vervolgens wordt `matrix` herhaaldelijk met die `factors`-matrix vermenigvuldigd (kruisproduct), tot het maximum van élke rij minstens de `ondergrens` haalt.

In [2]:
import numpy as np

def vermenigvuldig(matrix, factor, ondergrens):
    factors = np.zeros((matrix.shape))
    factors[:] = factor - 1
    for i in range(len(matrix[0])):
        factors[i, i] = factor

    while np.min(np.max(matrix, axis=0)) < ondergrens:
        matrix = np.dot(factors, matrix)

    return np.round(matrix, 1)

np.random.seed(10)
data = np.random.randint(1, 150, (5, 5))
uitkomst = vermenigvuldig(data, 1.2, 200)
print(uitkomst)
assert np.allclose(uitkomst, [[208.6, 324.6, 214.6, 263.6, 312.6],
       [317.2, 307.2, 202.2, 267.2, 194.2],
       [290. , 365. , 266. , 350. , 389. ],
       [317.8, 351.8, 370.8, 385.8, 325.8],
       [203.2, 270.2, 224.2, 247.2, 183.2]])

[[168.4 453.6 139.  329.6 313.2]
 [282.4 441.6 132.  338.6 200.2]
 [199.4 443.6 140.  365.6 339.2]
 [213.4 416.6 231.  387.6 262.2]
 [192.4 428.6 178.  342.6 213.2]]


AssertionError: 

**Wat gaat hier mis? Schrijf je antwoord + fix hieronder voor je verder scrolt.**