# 1B.1. Debug oefeningen — lees, voorspel, verbeter

Hieronder staan enkele korte, (bijna) volledige NumPy-functies. Er zit telkens **één** bug in die een foutief resultaat oplevert. Lees de code, **voorspel** de output, run de cel, en zoek de fout voor je de oplossing bekijkt.

Deze oefeningen zijn eenvoudiger dan de bugs in de voorbeeld-examenvragen — ideaal om de basissyntax van NumPy nog wat in te oefenen.

## Oefening 1: rij_sommen

Deze functie moet een lijst teruggeven met de som van elke **rij** van een matrix.

In [1]:
import numpy as np

def rij_sommen(matrix):
    """Geeft de som van elke rij terug."""
    return matrix.sum(axis=0)

matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
resultaat = rij_sommen(matrix)
print(resultaat)
assert list(resultaat) == [6, 15, 24]

[12 15 18]


AssertionError: 

**Wat gaat hier mis? Schrijf je antwoord + fix hieronder voor je verder scrolt.**

## Oefening 2: tel_boven_grens

Deze functie moet tellen hoeveel elementen van een matrix **strikt boven** een gegeven `grens` liggen.

In [2]:
import numpy as np

def tel_boven_grens(matrix, grens):
    """Telt hoeveel elementen strikt boven grens liggen."""
    return int(np.sum(matrix >= grens))

punten = np.array([[9, 13, 6, 1, 8, 12],
                    [16, 18, 14, 1, 11, 16],
                    [5, 10, 8, 6, 13, 14]])
aantal = tel_boven_grens(punten, 13)
print(aantal)
assert aantal == 5

7


AssertionError: 

**Wat gaat hier mis? Schrijf je antwoord + fix hieronder voor je verder scrolt.**

## Oefening 3: binnenmatrix

Deze functie moet de 'binnenste' matrix teruggeven: de originele matrix zonder de eerste/laatste rij, én zonder de eerste/laatste kolom.

In [3]:
import numpy as np

def binnenmatrix(matrix):
    """Geeft de matrix terug zonder buitenste rand."""
    return matrix[1:-1, 0:-1]

groot = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20],
                   [21, 22, 23, 24, 25]])
print(binnenmatrix(groot))
assert np.array_equal(binnenmatrix(groot), [[7, 8, 9],
                                             [12, 13, 14],
                                             [17, 18, 19]])

[[ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]]


AssertionError: 

**Wat gaat hier mis? Schrijf je antwoord + fix hieronder voor je verder scrolt.**