# NumPy

NumPy is een Python codebibliotheek die verscheidene wiskundige, voornamelijk algebraïsche, operaties implementeert. De onderliggende architectuur is gebaseerd op het gebruik van rijen (arrays) en matrices die vele malen sneller kunnen behandeld worden dan standaard lijsten omdat deze onderling vertaald worden naar C++ code. De matrices die opgesteld worden vormen de basis voor andere pakketten zoals pandas, scikit-learn, enz. Het is het Python antwoord op MatLab en deelt veel van de syntax. Meestal wordt NumPy als volgt geïmporteerd:

In [36]:
import numpy as np

## Aanmaken en basisoperaties

Een nieuwe, lege (als in, vol met nullen) rij/matrix kunnen als volgt gemaakt worden:

In [37]:
lege_rij = np.zeros(5)

print('Lege rij:', lege_rij)
print('Grootte van de rij:', lege_rij.shape)
print('Type van de rij:', type(lege_rij))

Lege rij: [0. 0. 0. 0. 0.]
Grootte van de rij: (5,)
Type van de rij: <class 'numpy.ndarray'>


In [38]:
lege_matrix = np.zeros((5,2))

print('Lege matrix:', lege_matrix)
print('Grootte van de dimensies van de matrix:', lege_matrix.shape)
print('Type van de matrix:', type(lege_matrix))

Lege matrix: [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Grootte van de dimensies van de matrix: (5, 2)
Type van de matrix: <class 'numpy.ndarray'>


Deze matrices kunnen dan makkelijk ingevuld worden:

In [39]:
lege_rij[2] = 4
lege_matrix[3,1] = 4

print('lege_rij:', lege_rij)
print('lege_matrix:', lege_matrix)

lege_rij: [0. 0. 4. 0. 0.]
lege_matrix: [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 4.]
 [0. 0.]]


Er zijn nog andere manieren om matrices aan te maken, bv.:
- `zeros()`: maakt een rij/matrix met allemaal 0-waardes
- `ones()`: maakt een rij/matrix met allemaal 1-waardes
- `empty()`: maakt een rij/matrix met willekeurige waardes
- `arange()`: maakt een rij/matrix volgens de logica van de `range()`-functie
- `linspace()`: maakt een reeks van getallen in een interval op dezelfde afstand naar gelang het aantal elementen gevraagd
- `random()`: maakt willekeurige reeksen

Deze worden hieronder geïllustreerd. Merk op dat je vaak een enkel getal kan opgeven voor een rij, of een tupel om het aantal rijen/kolommen van de matrix die je wilt maken. Daarnaast zijn er nog andere argumenten per functie, zoals te zien in de voorbeelden.

**Vaste-waarde matrices: `zeros()`, `ones()`, `empty()`**

In [40]:
# maak een rij met 10 nullen aan
rij = np.zeros(10)
rij

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
# maak een 5x3 matrix met nullen aan
# merk de analogie met shape: 
# (5,3) zet het 'shape'-attribuut van een ndarray vast 
matrix = np.zeros((5,3))
matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
# idem maar voor 1-waarden
rij1 = np.ones((4, 2))
rij1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [43]:
# empty werkt ook gelijkaardig
lege_matrix = np.empty((5, 5))
lege_matrix

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        8.90070287e-308, 1.33509100e-307],
       [1.42413555e-306, 1.78019082e-306, 1.37959740e-306,
        6.23057349e-307, 8.45593934e-307],
       [7.56593017e-307, 1.11258854e-306, 1.11261502e-306,
        1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 1.78018811e-306,
        1.33511562e-306, 8.90094053e-307],
       [9.34607074e-307, 1.20161118e-306, 2.22522596e-306,
        1.42410974e-306, 2.56761491e-312]])

**Reeksen met een patroon: `arange()` en `linspace()`**

In [44]:
# maak een interval van gehele getallen tussen 0 tot 10
interval1 = np.arange(10)
# idem, maar vanaf 5 en 10
interval2 = np.arange(5, 10)
# idem, maar vanaf -1 in stappen van 3
interval3 = np.arange(-1,10, 3)

print(interval1)
print(interval2)
print(interval3)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[-1  2  5  8]


In [45]:
# maak een reeks met gelijke intervallen tussen 10 tem 100
interval1 = np.linspace(10, 100)
# idem, maar vanaf 1 tem 10 met maar 3 waardes
interval2 = np.linspace(1, 10, 3)
# idem, maar vanaf 1 tem 20 met maar 6 waardes
interval3 = np.linspace(1, 20, 6)

print(interval1, 'lengte:', len(interval1)) # 50 is de default waarde
print(interval2)
print(interval3)

[ 10.          11.83673469  13.67346939  15.51020408  17.34693878
  19.18367347  21.02040816  22.85714286  24.69387755  26.53061224
  28.36734694  30.20408163  32.04081633  33.87755102  35.71428571
  37.55102041  39.3877551   41.2244898   43.06122449  44.89795918
  46.73469388  48.57142857  50.40816327  52.24489796  54.08163265
  55.91836735  57.75510204  59.59183673  61.42857143  63.26530612
  65.10204082  66.93877551  68.7755102   70.6122449   72.44897959
  74.28571429  76.12244898  77.95918367  79.79591837  81.63265306
  83.46938776  85.30612245  87.14285714  88.97959184  90.81632653
  92.65306122  94.48979592  96.32653061  98.16326531 100.        ] lengte: 50
[ 1.   5.5 10. ]
[ 1.   4.8  8.6 12.4 16.2 20. ]


**Willekeurige waarden: `np.random`**

In [46]:
# we zetten de seed, i.e., de willekeurige getallen gebruikt in de achtergrond
# voor herhaalbaarheid
np.random.seed(14)

# maak een reeks van 6 willekeurige gehele getallen vanaf 5 tot 10
willekeurige_gehele_rij = np.random.randint(5,10,6)

# maak een matrix van 3x6 met willekeurige gehele getallen vanaf 5 tot 10
willekeurige_gehele_matrix = np.random.randint(5,10, (3,6))

print('Rij:', willekeurige_gehele_rij)
print('Matrix:', willekeurige_gehele_matrix)

Rij: [8 5 9 6 7 9]
Matrix: [[7 5 5 7 6 8]
 [5 9 7 7 5 9]
 [5 6 5 8 9 8]]


In [47]:
# maak een reeks van 5 willekeurige getallen tussen 0 en 1
willekeurige_gehele_rij = np.random.rand(5)

# maak een matrix van 3x6 met willekeurige gehele getallen tussen 0 en 1
willekeurige_gehele_matrix = np.random.rand(5,6)

print('Rij:', willekeurige_gehele_rij)
print('Matrix:', willekeurige_gehele_matrix)

Rij: [0.11181193 0.17300409 0.79947421 0.91997165 0.5343132 ]
Matrix: [[0.09659772 0.11762231 0.26507861 0.71846493 0.17040221 0.98281146]
 [0.02680445 0.01156463 0.91525092 0.88347205 0.08143491 0.69675382]
 [0.68998065 0.98340857 0.65457965 0.18983453 0.81549226 0.36250668]
 [0.03986442 0.99614296 0.68017426 0.73534168 0.66120962 0.32712075]
 [0.73046609 0.18376514 0.45234358 0.22108777 0.49978794 0.71362252]]


## Berekeningen

### Snelheid: vectorisatie versus lussen

In de inleiding stond dat NumPy-berekeningen veel sneller kunnen verlopen dan met standaard Python-lijsten. Dit komt door *vectorisatie*: in plaats van element per element in een Python-lus te itereren, voert NumPy de berekening in één keer uit op de volledige array (onderliggend in C). Hieronder vergelijken we de som van een grote reeks getallen berekend met een Python-lus versus met de gevectoriseerde `sum()`-methode van NumPy:

In [48]:
import time

n = 5_000_000
lijst = list(range(n))
array = np.arange(n)

start = time.time()
totaal_lijst = 0
for getal in lijst:
    totaal_lijst += getal
tijd_lijst = time.time() - start

start = time.time()
totaal_array = array.sum()
tijd_array = time.time() - start

print(f'Som met Python-lus: {totaal_lijst} in {tijd_lijst:.4f} seconden')
print(f'Som met NumPy (gevectoriseerd): {totaal_array} in {tijd_array:.4f} seconden')
print(f'NumPy is hier ongeveer {tijd_lijst / tijd_array:.0f}x sneller')

Som met Python-lus: 12499997500000 in 0.3611 seconden
Som met NumPy (gevectoriseerd): 12499997500000 in 0.0020 seconden
NumPy is hier ongeveer 181x sneller


NumPy laat toe snel verschillende matrix-operaties uit te voeren. Merk hoe indexering wordt gecombineerd met standaard gedefinieerde attributen en attributen en methodes zoals ```T```, ```shape``` enz. Net zoals altijd telt NumPy ook vanaf 0 en niet vanaf 1:

In [49]:
mat = np.array([[1,3,3],[4,5,6],[7,8,9]])

print('Matrix:\n', mat)
print('Cell 2,2:', mat[1,1])
print('Cell 2,3:', mat[1,2])
print('Eerste 2 rijen:', mat[0:2])
# mat[0:2,] kan ook gebruikt worden voor de eerste 2 rijen
print('Eerste 2 kolommen:', mat[:,0:2])
print('Getransponeerde matrix:\n', mat.T)

Matrix:
 [[1 3 3]
 [4 5 6]
 [7 8 9]]
Cell 2,2: 5
Cell 2,3: 6
Eerste 2 rijen: [[1 3 3]
 [4 5 6]]
Eerste 2 kolommen: [[1 3]
 [4 5]
 [7 8]]
Getransponeerde matrix:
 [[1 4 7]
 [3 5 8]
 [3 6 9]]


Daarnaast bevat `numpy.linalg` functies voor lineaire algebra, zoals de inverse en de determinant van een (vierkante) matrix:

In [50]:
print('Inverteren (kan enkel op vierkante matrices):\n', np.linalg.inv(mat))
print('Determinant:\n', np.linalg.det(mat))

Inverteren (kan enkel op vierkante matrices):
 [[-0.5        -0.5         0.5       ]
 [ 1.         -2.          1.        ]
 [-0.5         2.16666667 -1.16666667]]
Determinant:
 6.0


Het `axis`-argument kan bij bijna alle berekeningen gebruikt worden om een bepaalde projectie over een as te maken. Zo kan je bv. de som maken enkel langs de rij-dimensie met `axis=0` (dus voor de kolommen) of langs de kolom-dimensie met `axis=1` (dus voor de rijen):

In [51]:
willekeurige_gehele_matrix = np.random.randint(5,10, (2,4))
print('Matrix:\n', willekeurige_gehele_matrix)

print('Totale som:',willekeurige_gehele_matrix.sum())
print('Som langs de rijen:', willekeurige_gehele_matrix.sum(axis=0))
print('Som langs de kolommen:', willekeurige_gehele_matrix.sum(axis=1))

Matrix:
 [[6 7 9 9]
 [8 5 6 5]]
Totale som: 55
Som langs de rijen: [14 12 15 14]
Som langs de kolommen: [31 24]


## Statistieken

In [52]:
mat_stat = np.array([[1,3,3],[4,5,6],[7,8,9]])

In [53]:
print('Totale som:', np.sum(mat_stat))
print('Hoogste getal:', np.max(mat_stat))
print('Hoogste getal per kolom (langs de rijen gaan):', np.max(mat_stat, axis=0))
print('Hoogste getal per rij (langs de kolommen gaan):', np.max(mat_stat, axis=1))
print('Laagste getal:', np.min(mat_stat))
print('Gemiddelde:', np.mean(mat_stat))
print('Mediaan:', np.median(mat_stat))
print('Standaard deviatie:', np.std(mat_stat))
print('Variantie:', np.var(mat_stat))

Totale som: 46
Hoogste getal: 9
Hoogste getal per kolom (langs de rijen gaan): [7 8 9]
Hoogste getal per rij (langs de kolommen gaan): [3 6 9]
Laagste getal: 1
Gemiddelde: 5.111111111111111
Mediaan: 5.0
Standaard deviatie: 2.469567863432541
Variantie: 6.098765432098765


Naast de waarde van het maximum/minimum kunnen we met `argmax()` en `argmin()` ook de *index* opvragen waar dat maximum/minimum zich bevindt. Zonder `axis`-argument wordt de matrix eerst plat (1D) gemaakt en gaat het over die platte index. `argsort()` geeft dan weer de indices terug die de reeks zouden sorteren, zonder de reeks zelf te sorteren:

In [54]:
print('Index van het hoogste getal (platte matrix):', np.argmax(mat_stat))
print('Index van het laagste getal per kolom:', np.argmin(mat_stat, axis=0))
print('Indices die de eerste rij zouden sorteren:', np.argsort(mat_stat[0]))

Index van het hoogste getal (platte matrix): 8
Index van het laagste getal per kolom: [0 0 0]
Indices die de eerste rij zouden sorteren: [0 1 2]


Deze functies combineren ook goed met indexering, bv. om de som van een specifieke rij of kolom te berekenen:

In [55]:
print('Som rij 1:', np.sum(mat_stat[0]))
print('Som rij 2:', np.sum(mat_stat[1]))
print('Som kolom 3:', np.sum(mat_stat[:,2]))

Som rij 1: 7
Som rij 2: 15
Som kolom 3: 18


## Matrix operaties

We maken vier arrays aan met verschillende vormen (`shape`) om te tonen hoe NumPy optelt en vermenigvuldigt: een 3x3-matrix (`mat_1`), een vector (`mat_2`), een andere 3x3-matrix (`mat_3`) en een 1x3-matrix (`mat_4`):

In [56]:
mat_1 = np.array([
    [1, 3, 3],
    [4, 5, 6],
    [7, 8, 9]])
mat_2 = np.array([4, 5, 6])
mat_3 = np.array([
    [5, 1, 1],
    [1, 0, 1],
    [5, 3, 4]])
mat_4 = np.array([[4, 5, 6]])
print('#rijen en #kolommen mat_1:', np.shape(mat_1))
print('#rijen en #kolommen mat_2 (vector):', np.shape(mat_2))
print('#rijen en #kolommen mat_4 (1x3 matrix):', np.shape(mat_4))
print('Som 1 & 4:', mat_1 + mat_4)
print('Som 1 & 3:', mat_1 + mat_3)

#rijen en #kolommen mat_1: (3, 3)
#rijen en #kolommen mat_2 (vector): (3,)
#rijen en #kolommen mat_4 (1x3 matrix): (1, 3)
Som 1 & 4: [[ 5  8  9]
 [ 8 10 12]
 [11 13 15]]
Som 1 & 3: [[ 6  4  4]
 [ 5  5  7]
 [12 11 13]]


`mat_1 + mat_4` werkt ondanks de verschillende vormen dankzij *broadcasting*: de 1x3-rij van `mat_4` wordt herhaald over de 3 rijen van `mat_1`. Verwar dit niet met vermenigvuldigen: `*` en `np.multiply()` werken element per element (met dezelfde broadcasting-regels), terwijl `np.dot()` (of het `@`-symbool) het echte matrixproduct uit de lineaire algebra berekent:

In [57]:
print('Elements-gewijze vermenigvuldiging 1 & 4:', mat_1 * mat_4)
print('Matrix product 1 & 2 ((3x3) * (3,) -> (3,)):', np.dot(mat_1, mat_2))
print('Elements-gewijze vermenigvuldiging 1 & 2:', np.multiply(mat_1, mat_2))
print('Matrix product 1 & 3 ((3x3) * (3x3) -> (3x3)):', np.dot(mat_1, mat_3))
# dit is equivalent:
print('Matrix product (met @) 1 & 3:', mat_1 @ mat_3)
print('Elements-gewijze vermenigvuldiging 1 & 3:', np.multiply(mat_1, mat_3))

Elements-gewijze vermenigvuldiging 1 & 4: [[ 4 15 18]
 [16 25 36]
 [28 40 54]]
Matrix product 1 & 2 ((3x3) * (3,) -> (3,)): [ 37  77 122]
Elements-gewijze vermenigvuldiging 1 & 2: [[ 4 15 18]
 [16 25 36]
 [28 40 54]]
Matrix product 1 & 3 ((3x3) * (3x3) -> (3x3)): [[23 10 16]
 [55 22 33]
 [88 34 51]]
Matrix product (met @) 1 & 3: [[23 10 16]
 [55 22 33]
 [88 34 51]]
Elements-gewijze vermenigvuldiging 1 & 3: [[ 5  3  3]
 [ 4  0  6]
 [35 24 36]]


Voor een matrixproduct moeten de dimensies overeenkomen: het aantal kolommen van de eerste matrix moet gelijk zijn aan het aantal rijen (of de lengte) van de tweede. `mat_2` (shape `(3,)`) voldoet hieraan, maar `mat_2.reshape((1,3))` (shape `(1,3)`) niet meer — dat geeft een `ValueError`, wat we hieronder opvangen om te tonen wat er dan gebeurt:

In [58]:
mat_2 = np.array([4, 5, 6])
print(mat_2.shape)
print(mat_2.reshape((1,3)).shape)
print('Matrix product 1 & 2:', np.dot(mat_1, mat_2))

# dit kan niet volgens de wiskunde (dimensies komen niet overeen):
try:
    np.dot(mat_1, mat_2.reshape((1,3)))
except ValueError as e:
    print('Fout:', e)

(3,)
(1, 3)
Matrix product 1 & 2: [ 37  77 122]
Fout: shapes (3,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)


## Hervormen en samenvoegen

Verder kunnen we ook makkelijk matrices bij elkaar voegen of hervormen:

In [59]:
reeks_1 = np.array([1,2,3,4,5,6])
reeks_2 = np.array([7,8,9,10,11,12])
reeks_1_2x3 = np.reshape(reeks_1, (2, 3))
reeks_2_2x3 = np.reshape(reeks_2, (2, 3))

print('Rij 1 als 1x6 matrix:\n', reeks_1)
print('Rij 1 als 2x3 matrix:\n', reeks_1_2x3)
print('Rij 2 als 2x3 matrix:\n', reeks_2_2x3)

Rij 1 als 1x6 matrix:
 [1 2 3 4 5 6]
Rij 1 als 2x3 matrix:
 [[1 2 3]
 [4 5 6]]
Rij 2 als 2x3 matrix:
 [[ 7  8  9]
 [10 11 12]]


Deze reeksen/matrices kunnen we vervolgens samenvoegen. Voor 1D-reeksen kan dit met `np.concatenate()`, maar voor 2D-matrices is het vaak intuïtiever om `np.vstack()` (verticaal, rijen onder elkaar) en `np.hstack()` (horizontaal, kolommen naast elkaar) te gebruiken — dat bespaart je het opzoeken van het juiste `axis`-argument:

In [60]:
print('Samengevoegd met concatenate (1D):', np.concatenate((reeks_1, reeks_2)))

print('\nSamengevoegd met vstack (rijen onder elkaar):\n', np.vstack((reeks_1_2x3, reeks_2_2x3)))
print('\nSamengevoegd met hstack (kolommen naast elkaar):\n', np.hstack((reeks_1_2x3, reeks_2_2x3)))

Samengevoegd met concatenate (1D): [ 1  2  3  4  5  6  7  8  9 10 11 12]

Samengevoegd met vstack (rijen onder elkaar):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Samengevoegd met hstack (kolommen naast elkaar):
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## Sorteren

Sorteren kan met de ingebouwde `np.sort()`-functie (dit is niet de gewone Python `sort()`-functie) die wordt toegepast langs de verschillende assen:

In [61]:
mat_sorteer = np.array([
    [10, 3, 3],
    [4, 5, 8],
    [9, 8, 7],
    [0, -2, 7]])

arr1 = np.sort(mat_sorteer, axis = 0)   
print('Gesorteerd langs de rijen (per kolom):', arr1)
arr2 = np.sort(mat_sorteer, axis = 1)   
print('Gesorteerd langs de kolommen (per rij):', arr2)
arr3 = np.sort(mat_sorteer, axis = None)    
print('Gesorteerd zonder as:', arr3)

Gesorteerd langs de rijen (per kolom): [[ 0 -2  3]
 [ 4  3  7]
 [ 9  5  7]
 [10  8  8]]
Gesorteerd langs de kolommen (per rij): [[ 3  3 10]
 [ 4  5  8]
 [ 7  8  9]
 [-2  0  7]]
Gesorteerd zonder as: [-2  0  3  3  4  5  7  7  8  8  9 10]


Merk op hoe de uitkomsten verschillende eindvormen kunnen aannemen. Dit kan bv. handig zijn als bv. de punten van verschillende vakken (kolommen) moeten worden gesorteerd tegelijk, of als machines (kolommen) moeten ingedeeld worden volgens hun omsteltijd voor bepaalde taken (per rij).

Om te weten welke unieke waarden in een reeks/matrix voorkomen, gebruik je `np.unique()`. Met het argument `return_counts=True` krijg je meteen ook het aantal keer dat elke waarde voorkomt (vergelijkbaar met `value_counts()` in Pandas, dat we later zien):

In [62]:
mat_uniek = np.array([1, 2, 2, 3, 3, 3, 4])

waarden = np.unique(mat_uniek)
print('Unieke waarden:', waarden)

waarden, aantallen = np.unique(mat_uniek, return_counts=True)
print('Unieke waarden:', waarden)
print('Aantal per waarde:', aantallen)

Unieke waarden: [1 2 3 4]
Unieke waarden: [1 2 3 4]
Aantal per waarde: [1 2 3 1]


## Filteren

NumPy biedt ook een reeks aan lambda-achtige functies om te filteren. Dit gebeurt via de `where()`-functie die wederom eerst een argument meekrijgt om mee te filteren (te behouden), bv. `mat_filter>2` om in de matrix `mat_filter` alle elementen groter dan 2 te behouden. Daarna kunnen we arumenten meegeven om aan te duiden wat te doen met de elementen die wel/niet aan deze conditie voldoen. We maken eerst een matrix aan:

In [63]:
mat_filter = np.array([1,2,3,4,5,6])

mat_filter = np.reshape(mat_filter, (2,3))
mat_filter

array([[1, 2, 3],
       [4, 5, 6]])

De eenvoudigste manier om te filteren is door de matrix direct te indexeren met een booleaanse conditie. `mat_filter > 2` geeft een matrix van dezelfde vorm terug met `True`/`False`-waarden; gebruik je die als index, dan krijg je enkel de elementen terug waar de conditie `True` is (als platte, 1D-reeks). Je kan dit ook gebruiken om waarden aan te passen die aan de conditie voldoen:

In [64]:
print('Booleaans masker:\n', mat_filter > 2)
print('Enkel de elementen > 2:', mat_filter[mat_filter > 2])

mat_filter_kopie = mat_filter.copy()
mat_filter_kopie[mat_filter_kopie > 2] = 0
print('Elementen > 2 vervangen door 0:\n', mat_filter_kopie)

Booleaans masker:
 [[False False  True]
 [ True  True  True]]
Enkel de elementen > 2: [3 4 5 6]
Elementen > 2 vervangen door 0:
 [[1 2 0]
 [0 0 0]]


Hier passen we `where()` toe met de conditie als eerste argument. Het tweede en derde argument duiden aan wat er moet komen op de plaats van de elementen waaraan de conditie voldaan is. Hier worden de elementen die niet voldoen aan de conditie vervangen door -10 en degene die voldoen vervangen door 10:

In [65]:
nieuwe_mat = np.where(mat_filter > 2, 10, -10)
nieuwe_mat

array([[-10, -10,  10],
       [ 10,  10,  10]])

Je kan ook de oorspronkelijke elementen behouden:

In [66]:
nieuwe_mat = np.where(mat_filter > 2, mat_filter, 10)
nieuwe_mat

array([[10, 10,  3],
       [ 4,  5,  6]])

Als je enkel de conditie meegeeft zal je enkel de indices van de elementen die voldoen terugkrijgen:

In [67]:
reeks_filter = np.array([7,8,9,10,11,12])
indices_reeks_filter = np.where(reeks_filter > 8)
indices_reeks_filter

(array([2, 3, 4, 5]),)

Deze kan je dan terug uit de originele `ndarray` kunnen halen via `take()`:

In [68]:
nieuwe_reeks_filter = np.take(reeks_filter, indices_reeks_filter)
nieuwe_reeks_filter

array([[ 9, 10, 11, 12]])

Voor een matrix krijg je de indices per dimensie mee, dus per rij en kolom:

In [69]:
indices_mat_filter = np.where(mat_filter > 2)
indices_mat_filter

(array([0, 1, 1, 1]), array([2, 0, 1, 2]))

Hierbij zijn dus de eerste elementen van deze lijsten de (0,2) voor rij 0, kolom 2 (daar staat 3), het tweede element is (1,0) voor rij 1, kolom 0 (daar staat 4), enz.

Dit kan NIET met `take()` worden gebruikt, maar gewoon `mat_filter[indices_mat_filter]`:

In [70]:
nieuwe_mat_filter = np.take(mat_filter, indices_mat_filter)
nieuwe_mat_filter

array([[1, 2, 2, 2],
       [3, 1, 2, 3]])